apiVersion: v1
kind: Service
metadata:
  name: survey-api
  namespace: ankiety-live
  labels:
    app.kubernetes.io/name: ankiety-live
    app.kubernetes.io/component: survey-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: survey-api
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: ankiety-live
  labels:
    app.kubernetes.io/name: ankiety-live
    app.kubernetes.io/component: voting-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: voting-service
  ports:
    - name: http
      port: 3001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: ankiety-live
  labels:
    app.kubernetes.io/name: ankiety-live
    app.kubernetes.io/component: websocket-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: websocket-server
  ports:
    - name: http
      port: 3002
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ankiety-live
  labels:
    app.kubernetes.io/name: ankiety-live
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
