apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ankiety-live
  namespace: ankiety-live
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ankiety-live.local
      secretName: ankiety-live-tls
  rules:
    - host: ankiety-live.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
