apiVersion: v1
kind: ResourceQuota
metadata:
  name: ankiety-quota
  namespace: ankiety-live
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "5"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "4"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ankiety-default-limits
  namespace: ankiety-live
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 768Mi
